export const productos = [
  {
    id: 1,
    nombre: "Palta Hass Ecológica",
    precio: 2.5,
    stock: 40,
  },
  {
    id: 2,
    nombre: "Aceite de Oliva Virgen Extra",
    precio: 8.9,
    stock: 25,
  },
  {
    id: 3,
    nombre: "Mix de Frutos Secos Naturales 250g",
    precio: 4.5,
    stock: 50,
  },
  {
    id: 4,
    nombre: "Pan Integral Artesanal",
    precio: 3.2,
    stock: 30,
  },
  {
    id: 5,
    nombre: "Miel Pura de Abeja 500g",
    precio: 6.8,
    stock: 20,
  },
  {
    id: 6,
    nombre: "Harina de Avena Orgánica 1kg",
    precio: 3.9,
    stock: 35,
  },
  {
    id: 7,
    nombre: "Yogur Natural sin Azúcar 500ml",
    precio: 2.1,
    stock: 15,
  },
  {
    id: 8,
    nombre: "Granola Casera con Semillas 300g",
    precio: 4.7,
    stock: 28,
  },
  {
    id: 9,
    nombre: "Té Verde Orgánico 20u",
    precio: 5.2,
    stock: 22,
  },
  {
    id: 10,
    nombre: "Mantequilla de Maní Natural 350g",
    precio: 5.9,
    stock: 18,
  },
  {
    id: 11,
    nombre: "Leche de Almendras sin Azúcar 1L",
    precio: 3.4,
    stock: 25,
  },
  {
    id: 12,
    nombre: "Semillas de Chía Orgánicas 200g",
    precio: 2.8,
    stock: 40,
  },
  {
    id: 13,
    nombre: "Barra Energética Natural de Cacao",
    precio: 1.9,
    stock: 60,
  },
  {
    id: 14,
    nombre: "Harina Integral de Espelta 1kg",
    precio: 3.6,
    stock: 35,
  },
  {
    id: 15,
    nombre: "Aceite de Coco Virgen 400ml",
    precio: 6.5,
    stock: 22,
  },
  {
    id: 16,
    nombre: "Vinagre de Manzana Orgánico 500ml",
    precio: 4.2,
    stock: 28,
  },
  {
    id: 17,
    nombre: "Avena Instantánea sin Gluten 1kg",
    precio: 3.8,
    stock: 30,
  },
  {
    id: 18,
    nombre: "Pasta Integral de Trigo Duro 500g",
    precio: 2.3,
    stock: 45,
  },
  {
    id: 19,
    nombre: "Granola con Frutos Rojos 300g",
    precio: 4.9,
    stock: 26,
  },
  {
    id: 20,
    nombre: "Tostadas de Arroz Integral 150g",
    precio: 2.1,
    stock: 38,
  },
];
